# Generated by Django 5.0.4 on 2024-04-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=200, null=True)),
                ('product_quantity', models.IntegerField(default=0)),
                ('product_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Repaired')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'product_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InHandStock',
            fields=[
                ('ihs_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_type', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'inhand_stock_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DailyInventory',
            fields=[
                ('di_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'daily_inventory_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RejectedProduct',
            fields=[
                ('rj_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'rejected_product_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RepairProduct',
            fields=[
                ('rp_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_started', models.DateField()),
                ('rp_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active'), (2, 'Repaired')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'db_table': 'repair_product_table',
                'managed': True,
            },
        ),
    ]
