# Generated by Django 5.0.4 on 2024-04-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinventory',
            name='status',
            field=models.IntegerField(choices=[(1, 'Packed'), (2, 'Dispatched'), (3, 'Returned')], default=1),
        ),
    ]
