# Generated by Django 5.0.4 on 2024-04-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_repairproduct_date_finished_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTracking',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('event_date', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Packed'), (2, 'Dispatched'), (3, 'Returned')], default=1)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(default='0')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.IntegerField(default='0')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.IntegerField(default='0')),
            ],
            options={
                'db_table': 'product_tracking_table',
                'managed': True,
            },
        ),
    ]
